# -*- coding: utf-8 -*-
"""Wind Speed Tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uh-usr9jlX2D2fWwOhDY9JAkyktXIpci
"""

from gpiozero import Button
import time
import math

wind_speed_sensor = Button(5) #this will store the number of rotations. the 5 means it is set up on GPIO 5
wind_count = 0

def spin():
  global wind_count #will run when the anemometer spins
  wind_count = wind_count + 1
  print("spin" + str(windconstant))

wind_speed_sensor.when_pressed = spin

radius_cm = 9.0 # radius of the anemometer
wind_interval = 5 # how often speed is reported in seconds

def calculate_speed(time_sec):
  global wind_count
  circumference_cm = (2 * math.pi) * radius_cm
  rotations = wind_count / 2.0
  distance_cm = circumference_cm * rotations
  speed = distance_cm / time_sec

  return speed