# -*- coding: utf-8 -*-
"""Wind Speed Tracker (Calibrated).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uh-usr9jlX2D2fWwOhDY9JAkyktXIpci
"""

from gpiozero import Button
import time
import math

wind_speed_sensor = Button(5) #this will store the number of rotations. the 5 means it is set up on GPIO 5
def reset_wind():
  global wind_count
  wind_count = 0 #resets the wind count every time it starts again

def spin():
  global wind_count #will run when the anemometer spins
  wind_count = wind_count + 1
  print("spin" + str(windconstant))

wind_speed_sensor.when_pressed = spin

radius_cm = 9.0 # radius of the anemometer
wind_interval = 5 # how often speed is reported in seconds

adjustment = 1.18 #from calibration off the first program
cm_in_km = 100000.0
sec_in_hour= 3600

def calculate_speed(time_sec):
  global wind_count
  circumference_cm = (2 * math.pi) * radius_cm
  rotations = wind_count / 2.0

  distance_km = (circumference_cm * rotations) / cm_in_km

  km_per_sec = distance_km / time_sec
  km_per_hour = km_per_sec * sec_in_hour

  return km_per_hour * adjustment